const doctors = [
  {
    id: '1',
    name: 'Dr. Sarah Wilson',
    email: 'sarah.wilson@hospital.com',
    password: 'sarah123',
    specialty: 'Cardiology',
    experience: 15,
    degrees: ['MD Cardiology', 'Fellowship in Interventional Cardiology'],
    achievements: ['Best Cardiologist Award 2023', 'Published 50+ Research Papers'],
    rating: 4.9,
    reviews: 245,
    image: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '6',
    name: 'Dr. Rahul Mehra',
    email: 'rahul.mehra@hospital.com',
    password: 'rahul123',
    specialty: 'Cardiology',
    experience: 17,
    degrees: ['MD Cardiology', 'DM Cardiovascular Medicine'],
    achievements: ['Top Innovator in Cardiac Devices 2022'],
    rating: 4.8,
    reviews: 230,
    image: 'https://images.pexels.com/photos/8376296/pexels-photo-8376296.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '2',
    name: 'Dr. Michael Chen',
    email: 'michael.chen@hospital.com',
    password: 'michael123',
    specialty: 'Dermatology',
    experience: 12,
    degrees: ['MD Dermatology', 'Board Certified Dermatologist'],
    achievements: ['Excellence in Skin Care Award', 'Top 10 Dermatologists 2023'],
    rating: 4.8,
    reviews: 189,
    image: 'https://images.pexels.com/photos/6129967/pexels-photo-6129967.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '7',
    name: 'Dr. Anjali Verma',
    email: 'anjali.verma@hospital.com',
    password: 'anjali123',
    specialty: 'Dermatology',
    experience: 10,
    degrees: ['MD Dermatology'],
    achievements: ['Best Young Dermatologist 2021'],
    rating: 4.7,
    reviews: 175,
    image: 'https://images.pexels.com/photos/8460158/pexels-photo-8460158.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: false,
  },
  {
    id: '3',
    name: 'Dr. Emily Rodriguez',
    email: 'emily.rodriguez@hospital.com',
    password: 'emily123',
    specialty: 'Orthopedics',
    experience: 18,
    degrees: ['MD Orthopedic Surgery', 'Fellowship in Sports Medicine'],
    achievements: ['Orthopedic Surgeon of the Year', 'Innovation in Joint Replacement'],
    rating: 4.9,
    reviews: 312,
    image: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '8',
    name: 'Dr. Rajiv Patel',
    email: 'rajiv.patel@hospital.com',
    password: 'rajiv123',
    specialty: 'Orthopedics',
    experience: 14,
    degrees: ['MS Orthopedics'],
    achievements: ['Joint Replacement Pioneer 2020'],
    rating: 4.6,
    reviews: 198,
    image: 'https://images.pexels.com/photos/6749775/pexels-photo-6749775.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '4',
    name: 'Dr. James Thompson',
    email: 'james.thompson@hospital.com',
    password: 'james123',
    specialty: 'General Medicine',
    experience: 20,
    degrees: ['MD Internal Medicine', 'Board Certified Family Medicine'],
    achievements: ['Community Service Award', '25 Years of Excellence'],
    rating: 4.7,
    reviews: 567,
    image: 'https://images.pexels.com/photos/5407206/pexels-photo-5407206.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '9',
    name: 'Dr. Neha Singhania',
    email: 'neha.singhania@hospital.com',
    password: 'neha123',
    specialty: 'General Medicine',
    experience: 11,
    degrees: ['MBBS', 'MD General Medicine'],
    achievements: ['Young Physician Award 2022'],
    rating: 4.8,
    reviews: 240,
    image: 'https://images.pexels.com/photos/8460086/pexels-photo-8460086.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '5',
    name: 'Dr. Lisa Park',
    email: 'lisa.park@hospital.com',
    password: 'lisa123',
    specialty: 'Pediatrics',
    experience: 14,
    degrees: ['MD Pediatrics', 'Fellowship in Pediatric Cardiology'],
    achievements: ['Child Care Excellence Award', 'Best Pediatrician 2023'],
    rating: 4.9,
    reviews: 298,
    image: 'https://images.pexels.com/photos/5452201/pexels-photo-5452201.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '10',
    name: 'Dr. Vikram Joshi',
    email: 'vikram.joshi@hospital.com',
    password: 'vikram123',
    specialty: 'Pediatrics',
    experience: 9,
    degrees: ['MD Pediatrics'],
    achievements: ['National Immunization Champion'],
    rating: 4.6,
    reviews: 190,
    image: 'https://images.pexels.com/photos/8376266/pexels-photo-8376266.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  }
];

const appointments = [
  {
    id: '1',
    patientName: 'John Smith',
    age: 45,
    phone: '(555) 123-4567',
    email: 'john.smith@email.com',
    address: '123 Main St, City, State',
    disease: 'Chest Pain',
    preferredDoctor: 'Dr. Sarah Wilson',
    timeSlot: '09:00 AM',
    date: '2024-01-15',
    status: 'confirmed',
  },
  {
    id: '2',
    patientName: 'Mary Johnson',
    age: 32,
    phone: '(555) 987-6543',
    email: 'mary.johnson@email.com',
    address: '456 Oak Ave, City, State',
    disease: 'Skin Rash',
    preferredDoctor: 'Dr. Michael Chen',
    timeSlot: '10:30 AM',
    date: '2024-01-15',
    status: 'pending',
  },
];

// 🔒 Allowed doctor login list (for AuthContext check or login.tsx)
const allowedDoctors = doctors.map(({ email, password, name, id }) => ({
  email,
  password,
  name,
  doctorId: id
}));

module.exports = {
  doctors,
  appointments,
  allowedDoctors
};